version: '2'  
services:

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: docker
      POSTGRES_DB: eventsmap
    ports:
      - 5432